// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fir_wrap_fir_wrap,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=29758,HLS_SYN_LUT=10093,HLS_VERSION=2023_1}" *)

module fir_wrap (
        ap_clk,
        ap_rst_n,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP,
        interrupt,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP
);

parameter    ap_ST_fsm_state1 = 26'd1;
parameter    ap_ST_fsm_state2 = 26'd2;
parameter    ap_ST_fsm_state3 = 26'd4;
parameter    ap_ST_fsm_state4 = 26'd8;
parameter    ap_ST_fsm_state5 = 26'd16;
parameter    ap_ST_fsm_state6 = 26'd32;
parameter    ap_ST_fsm_state7 = 26'd64;
parameter    ap_ST_fsm_state8 = 26'd128;
parameter    ap_ST_fsm_state9 = 26'd256;
parameter    ap_ST_fsm_state10 = 26'd512;
parameter    ap_ST_fsm_state11 = 26'd1024;
parameter    ap_ST_fsm_state12 = 26'd2048;
parameter    ap_ST_fsm_state13 = 26'd4096;
parameter    ap_ST_fsm_state14 = 26'd8192;
parameter    ap_ST_fsm_state15 = 26'd16384;
parameter    ap_ST_fsm_state16 = 26'd32768;
parameter    ap_ST_fsm_state17 = 26'd65536;
parameter    ap_ST_fsm_state18 = 26'd131072;
parameter    ap_ST_fsm_state19 = 26'd262144;
parameter    ap_ST_fsm_state20 = 26'd524288;
parameter    ap_ST_fsm_state21 = 26'd1048576;
parameter    ap_ST_fsm_state22 = 26'd2097152;
parameter    ap_ST_fsm_state23 = 26'd4194304;
parameter    ap_ST_fsm_state24 = 26'd8388608;
parameter    ap_ST_fsm_state25 = 26'd16777216;
parameter    ap_ST_fsm_state26 = 26'd33554432;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;
output   interrupt;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [25:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] y;
wire   [63:0] x;
wire   [31:0] len;
wire   [63:0] coef;
reg   [31:0] c_0;
reg   [31:0] c_1;
reg   [31:0] c_2;
reg   [31:0] c_3;
reg   [31:0] c_4;
reg   [31:0] c_5;
reg   [31:0] c_6;
reg   [31:0] c_7;
reg   [31:0] c_8;
reg   [31:0] c_9;
reg   [31:0] c_10;
reg   [31:0] c_11;
reg   [31:0] c_12;
reg   [31:0] c_13;
reg   [31:0] c_14;
reg   [31:0] c_15;
reg   [31:0] c_16;
reg   [31:0] c_17;
reg   [31:0] c_18;
reg   [31:0] c_19;
reg   [31:0] c_20;
reg   [31:0] c_21;
reg   [31:0] c_22;
reg   [31:0] c_23;
reg   [31:0] c_24;
reg   [31:0] c_25;
reg   [31:0] c_26;
reg   [31:0] c_27;
reg   [31:0] c_28;
reg   [31:0] c_29;
reg   [31:0] c_30;
reg   [31:0] c_31;
reg   [31:0] c_32;
reg   [31:0] c_33;
reg   [31:0] c_34;
reg   [31:0] c_35;
reg   [31:0] c_36;
reg   [31:0] c_37;
reg   [31:0] c_38;
reg   [31:0] c_39;
reg   [31:0] c_40;
reg   [31:0] c_41;
reg   [31:0] c_42;
reg   [31:0] c_43;
reg   [31:0] c_44;
reg   [31:0] c_45;
reg   [31:0] c_46;
reg   [31:0] c_47;
reg   [31:0] c_48;
reg   [31:0] c_49;
reg   [31:0] c_50;
reg   [31:0] c_51;
reg   [31:0] c_52;
reg   [31:0] c_53;
reg   [31:0] c_54;
reg   [31:0] c_55;
reg   [31:0] c_56;
reg   [31:0] c_57;
reg   [31:0] c_58;
reg   [31:0] c_59;
reg   [31:0] c_60;
reg   [31:0] c_61;
reg   [31:0] c_62;
reg   [31:0] c_63;
reg   [31:0] c_64;
reg   [31:0] c_65;
reg   [31:0] c_66;
reg   [31:0] c_67;
reg   [31:0] c_68;
reg   [31:0] c_69;
reg   [31:0] c_70;
reg   [31:0] c_71;
reg   [31:0] c_72;
reg   [31:0] c_73;
reg   [31:0] c_74;
reg   [31:0] c_75;
reg   [31:0] c_76;
reg   [31:0] c_77;
reg   [31:0] c_78;
reg   [31:0] c_79;
reg   [31:0] c_80;
reg   [31:0] c_81;
reg   [31:0] c_82;
reg   [31:0] c_83;
reg   [31:0] c_84;
reg   [31:0] c_85;
reg   [31:0] c_86;
reg   [31:0] c_87;
reg   [31:0] c_88;
reg   [31:0] c_89;
reg   [31:0] c_90;
reg   [31:0] c_91;
reg   [31:0] c_92;
reg   [31:0] c_93;
reg   [31:0] c_94;
reg   [31:0] c_95;
reg   [31:0] c_96;
reg   [31:0] c_97;
reg   [31:0] c_98;
reg    gmem_blk_n_AR;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state12;
reg    gmem_blk_n_AW;
wire    ap_CS_fsm_state19;
reg    gmem_blk_n_B;
wire    ap_CS_fsm_state26;
reg   [31:0] len_read_reg_1200;
wire   [30:0] trunc_ln31_fu_1120_p1;
reg   [30:0] trunc_ln31_reg_1206;
reg   [61:0] trunc_ln41_1_reg_1211;
reg   [61:0] trunc_ln1_reg_1217;
reg   [61:0] trunc_ln47_1_reg_1223;
wire   [30:0] empty_63_fu_1169_p3;
reg   [30:0] empty_63_reg_1234;
wire    ap_CS_fsm_state11;
wire   [31:0] zext_ln47_fu_1186_p1;
reg   [31:0] zext_ln47_reg_1244;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_ap_start;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_ap_done;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_ap_idle;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_ap_ready;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_AWVALID;
wire   [63:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_AWADDR;
wire   [0:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_AWID;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_AWLEN;
wire   [2:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_AWSIZE;
wire   [1:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_AWBURST;
wire   [1:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_AWLOCK;
wire   [3:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_AWCACHE;
wire   [2:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_AWPROT;
wire   [3:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_AWQOS;
wire   [3:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_AWREGION;
wire   [0:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_AWUSER;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_WVALID;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_WDATA;
wire   [3:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_WSTRB;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_WLAST;
wire   [0:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_WID;
wire   [0:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_WUSER;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_ARVALID;
wire   [63:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_ARADDR;
wire   [0:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_ARID;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_ARLEN;
wire   [2:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_ARSIZE;
wire   [1:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_ARBURST;
wire   [1:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_ARLOCK;
wire   [3:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_ARCACHE;
wire   [2:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_ARPROT;
wire   [3:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_ARQOS;
wire   [3:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_ARREGION;
wire   [0:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_ARUSER;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_RREADY;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_BREADY;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_0;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_0_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_1;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_1_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_2;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_2_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_3;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_3_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_4;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_4_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_5;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_5_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_6;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_6_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_7;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_7_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_8;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_8_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_9;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_9_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_10;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_10_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_11;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_11_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_12;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_12_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_13;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_13_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_14;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_14_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_15;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_15_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_16;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_16_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_17;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_17_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_18;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_18_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_19;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_19_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_20;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_20_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_21;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_21_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_22;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_22_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_23;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_23_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_24;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_24_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_25;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_25_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_26;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_26_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_27;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_27_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_28;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_28_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_29;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_29_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_30;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_30_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_31;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_31_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_32;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_32_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_33;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_33_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_34;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_34_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_35;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_35_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_36;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_36_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_37;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_37_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_38;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_38_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_39;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_39_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_40;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_40_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_41;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_41_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_42;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_42_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_43;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_43_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_44;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_44_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_45;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_45_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_46;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_46_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_47;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_47_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_48;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_48_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_49;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_49_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_50;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_50_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_51;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_51_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_52;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_52_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_53;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_53_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_54;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_54_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_55;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_55_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_56;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_56_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_57;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_57_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_58;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_58_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_59;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_59_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_60;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_60_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_61;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_61_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_62;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_62_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_63;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_63_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_64;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_64_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_65;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_65_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_66;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_66_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_67;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_67_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_68;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_68_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_69;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_69_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_70;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_70_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_71;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_71_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_72;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_72_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_73;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_73_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_74;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_74_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_75;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_75_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_76;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_76_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_77;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_77_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_78;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_78_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_79;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_79_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_80;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_80_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_81;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_81_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_82;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_82_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_83;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_83_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_84;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_84_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_85;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_85_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_86;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_86_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_87;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_87_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_88;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_88_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_89;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_89_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_90;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_90_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_91;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_91_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_92;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_92_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_93;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_93_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_94;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_94_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_95;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_95_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_96;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_96_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_97;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_97_ap_vld;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_98;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_98_ap_vld;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_ap_start;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_ap_done;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_ap_idle;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_ap_ready;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_AWVALID;
wire   [63:0] grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_AWADDR;
wire   [0:0] grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_AWID;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_AWLEN;
wire   [2:0] grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_AWSIZE;
wire   [1:0] grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_AWBURST;
wire   [1:0] grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_AWLOCK;
wire   [3:0] grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_AWCACHE;
wire   [2:0] grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_AWPROT;
wire   [3:0] grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_AWQOS;
wire   [3:0] grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_AWREGION;
wire   [0:0] grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_AWUSER;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_WVALID;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_WDATA;
wire   [3:0] grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_WSTRB;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_WLAST;
wire   [0:0] grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_WID;
wire   [0:0] grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_WUSER;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_ARVALID;
wire   [63:0] grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_ARADDR;
wire   [0:0] grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_ARID;
wire   [31:0] grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_ARLEN;
wire   [2:0] grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_ARSIZE;
wire   [1:0] grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_ARBURST;
wire   [1:0] grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_ARLOCK;
wire   [3:0] grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_ARCACHE;
wire   [2:0] grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_ARPROT;
wire   [3:0] grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_ARQOS;
wire   [3:0] grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_ARREGION;
wire   [0:0] grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_ARUSER;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_RREADY;
wire    grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_BREADY;
reg    gmem_AWVALID;
wire    gmem_AWREADY;
reg   [63:0] gmem_AWADDR;
reg   [31:0] gmem_AWLEN;
reg    gmem_WVALID;
wire    gmem_WREADY;
reg    gmem_ARVALID;
wire    gmem_ARREADY;
reg   [63:0] gmem_ARADDR;
reg   [31:0] gmem_ARLEN;
wire    gmem_RVALID;
reg    gmem_RREADY;
wire   [31:0] gmem_RDATA;
wire   [8:0] gmem_RFIFONUM;
wire    gmem_BVALID;
reg    gmem_BREADY;
reg    grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_ap_start_reg;
wire    ap_CS_fsm_state10;
reg    grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_ap_start_reg;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state21;
wire  signed [63:0] sext_ln41_fu_1154_p1;
wire  signed [63:0] sext_ln47_fu_1176_p1;
wire  signed [63:0] sext_ln47_1_fu_1190_p1;
wire   [0:0] icmp_ln47_fu_1164_p2;
reg   [25:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
reg    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
reg    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
reg    ap_ST_fsm_state26_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 26'd1;
#0 c_0 = 32'd0;
#0 c_1 = 32'd0;
#0 c_2 = 32'd0;
#0 c_3 = 32'd0;
#0 c_4 = 32'd0;
#0 c_5 = 32'd0;
#0 c_6 = 32'd0;
#0 c_7 = 32'd0;
#0 c_8 = 32'd0;
#0 c_9 = 32'd0;
#0 c_10 = 32'd0;
#0 c_11 = 32'd0;
#0 c_12 = 32'd0;
#0 c_13 = 32'd0;
#0 c_14 = 32'd0;
#0 c_15 = 32'd0;
#0 c_16 = 32'd0;
#0 c_17 = 32'd0;
#0 c_18 = 32'd0;
#0 c_19 = 32'd0;
#0 c_20 = 32'd0;
#0 c_21 = 32'd0;
#0 c_22 = 32'd0;
#0 c_23 = 32'd0;
#0 c_24 = 32'd0;
#0 c_25 = 32'd0;
#0 c_26 = 32'd0;
#0 c_27 = 32'd0;
#0 c_28 = 32'd0;
#0 c_29 = 32'd0;
#0 c_30 = 32'd0;
#0 c_31 = 32'd0;
#0 c_32 = 32'd0;
#0 c_33 = 32'd0;
#0 c_34 = 32'd0;
#0 c_35 = 32'd0;
#0 c_36 = 32'd0;
#0 c_37 = 32'd0;
#0 c_38 = 32'd0;
#0 c_39 = 32'd0;
#0 c_40 = 32'd0;
#0 c_41 = 32'd0;
#0 c_42 = 32'd0;
#0 c_43 = 32'd0;
#0 c_44 = 32'd0;
#0 c_45 = 32'd0;
#0 c_46 = 32'd0;
#0 c_47 = 32'd0;
#0 c_48 = 32'd0;
#0 c_49 = 32'd0;
#0 c_50 = 32'd0;
#0 c_51 = 32'd0;
#0 c_52 = 32'd0;
#0 c_53 = 32'd0;
#0 c_54 = 32'd0;
#0 c_55 = 32'd0;
#0 c_56 = 32'd0;
#0 c_57 = 32'd0;
#0 c_58 = 32'd0;
#0 c_59 = 32'd0;
#0 c_60 = 32'd0;
#0 c_61 = 32'd0;
#0 c_62 = 32'd0;
#0 c_63 = 32'd0;
#0 c_64 = 32'd0;
#0 c_65 = 32'd0;
#0 c_66 = 32'd0;
#0 c_67 = 32'd0;
#0 c_68 = 32'd0;
#0 c_69 = 32'd0;
#0 c_70 = 32'd0;
#0 c_71 = 32'd0;
#0 c_72 = 32'd0;
#0 c_73 = 32'd0;
#0 c_74 = 32'd0;
#0 c_75 = 32'd0;
#0 c_76 = 32'd0;
#0 c_77 = 32'd0;
#0 c_78 = 32'd0;
#0 c_79 = 32'd0;
#0 c_80 = 32'd0;
#0 c_81 = 32'd0;
#0 c_82 = 32'd0;
#0 c_83 = 32'd0;
#0 c_84 = 32'd0;
#0 c_85 = 32'd0;
#0 c_86 = 32'd0;
#0 c_87 = 32'd0;
#0 c_88 = 32'd0;
#0 c_89 = 32'd0;
#0 c_90 = 32'd0;
#0 c_91 = 32'd0;
#0 c_92 = 32'd0;
#0 c_93 = 32'd0;
#0 c_94 = 32'd0;
#0 c_95 = 32'd0;
#0 c_96 = 32'd0;
#0 c_97 = 32'd0;
#0 c_98 = 32'd0;
#0 grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_ap_start_reg = 1'b0;
#0 grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_ap_start_reg = 1'b0;
end

fir_wrap_fir_wrap_Pipeline_VITIS_LOOP_41_1 grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_ap_start),
    .ap_done(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_ap_done),
    .ap_idle(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_ap_idle),
    .ap_ready(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_ap_ready),
    .m_axi_gmem_AWVALID(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(gmem_RVALID),
    .m_axi_gmem_RREADY(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(gmem_RDATA),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RFIFONUM(gmem_RFIFONUM),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .sext_ln41(trunc_ln41_1_reg_1211),
    .c_0(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_0),
    .c_0_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_0_ap_vld),
    .c_1(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_1),
    .c_1_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_1_ap_vld),
    .c_2(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_2),
    .c_2_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_2_ap_vld),
    .c_3(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_3),
    .c_3_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_3_ap_vld),
    .c_4(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_4),
    .c_4_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_4_ap_vld),
    .c_5(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_5),
    .c_5_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_5_ap_vld),
    .c_6(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_6),
    .c_6_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_6_ap_vld),
    .c_7(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_7),
    .c_7_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_7_ap_vld),
    .c_8(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_8),
    .c_8_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_8_ap_vld),
    .c_9(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_9),
    .c_9_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_9_ap_vld),
    .c_10(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_10),
    .c_10_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_10_ap_vld),
    .c_11(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_11),
    .c_11_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_11_ap_vld),
    .c_12(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_12),
    .c_12_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_12_ap_vld),
    .c_13(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_13),
    .c_13_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_13_ap_vld),
    .c_14(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_14),
    .c_14_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_14_ap_vld),
    .c_15(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_15),
    .c_15_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_15_ap_vld),
    .c_16(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_16),
    .c_16_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_16_ap_vld),
    .c_17(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_17),
    .c_17_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_17_ap_vld),
    .c_18(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_18),
    .c_18_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_18_ap_vld),
    .c_19(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_19),
    .c_19_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_19_ap_vld),
    .c_20(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_20),
    .c_20_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_20_ap_vld),
    .c_21(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_21),
    .c_21_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_21_ap_vld),
    .c_22(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_22),
    .c_22_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_22_ap_vld),
    .c_23(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_23),
    .c_23_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_23_ap_vld),
    .c_24(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_24),
    .c_24_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_24_ap_vld),
    .c_25(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_25),
    .c_25_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_25_ap_vld),
    .c_26(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_26),
    .c_26_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_26_ap_vld),
    .c_27(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_27),
    .c_27_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_27_ap_vld),
    .c_28(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_28),
    .c_28_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_28_ap_vld),
    .c_29(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_29),
    .c_29_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_29_ap_vld),
    .c_30(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_30),
    .c_30_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_30_ap_vld),
    .c_31(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_31),
    .c_31_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_31_ap_vld),
    .c_32(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_32),
    .c_32_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_32_ap_vld),
    .c_33(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_33),
    .c_33_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_33_ap_vld),
    .c_34(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_34),
    .c_34_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_34_ap_vld),
    .c_35(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_35),
    .c_35_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_35_ap_vld),
    .c_36(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_36),
    .c_36_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_36_ap_vld),
    .c_37(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_37),
    .c_37_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_37_ap_vld),
    .c_38(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_38),
    .c_38_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_38_ap_vld),
    .c_39(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_39),
    .c_39_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_39_ap_vld),
    .c_40(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_40),
    .c_40_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_40_ap_vld),
    .c_41(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_41),
    .c_41_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_41_ap_vld),
    .c_42(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_42),
    .c_42_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_42_ap_vld),
    .c_43(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_43),
    .c_43_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_43_ap_vld),
    .c_44(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_44),
    .c_44_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_44_ap_vld),
    .c_45(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_45),
    .c_45_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_45_ap_vld),
    .c_46(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_46),
    .c_46_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_46_ap_vld),
    .c_47(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_47),
    .c_47_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_47_ap_vld),
    .c_48(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_48),
    .c_48_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_48_ap_vld),
    .c_49(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_49),
    .c_49_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_49_ap_vld),
    .c_50(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_50),
    .c_50_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_50_ap_vld),
    .c_51(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_51),
    .c_51_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_51_ap_vld),
    .c_52(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_52),
    .c_52_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_52_ap_vld),
    .c_53(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_53),
    .c_53_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_53_ap_vld),
    .c_54(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_54),
    .c_54_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_54_ap_vld),
    .c_55(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_55),
    .c_55_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_55_ap_vld),
    .c_56(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_56),
    .c_56_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_56_ap_vld),
    .c_57(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_57),
    .c_57_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_57_ap_vld),
    .c_58(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_58),
    .c_58_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_58_ap_vld),
    .c_59(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_59),
    .c_59_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_59_ap_vld),
    .c_60(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_60),
    .c_60_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_60_ap_vld),
    .c_61(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_61),
    .c_61_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_61_ap_vld),
    .c_62(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_62),
    .c_62_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_62_ap_vld),
    .c_63(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_63),
    .c_63_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_63_ap_vld),
    .c_64(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_64),
    .c_64_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_64_ap_vld),
    .c_65(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_65),
    .c_65_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_65_ap_vld),
    .c_66(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_66),
    .c_66_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_66_ap_vld),
    .c_67(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_67),
    .c_67_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_67_ap_vld),
    .c_68(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_68),
    .c_68_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_68_ap_vld),
    .c_69(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_69),
    .c_69_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_69_ap_vld),
    .c_70(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_70),
    .c_70_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_70_ap_vld),
    .c_71(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_71),
    .c_71_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_71_ap_vld),
    .c_72(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_72),
    .c_72_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_72_ap_vld),
    .c_73(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_73),
    .c_73_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_73_ap_vld),
    .c_74(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_74),
    .c_74_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_74_ap_vld),
    .c_75(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_75),
    .c_75_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_75_ap_vld),
    .c_76(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_76),
    .c_76_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_76_ap_vld),
    .c_77(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_77),
    .c_77_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_77_ap_vld),
    .c_78(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_78),
    .c_78_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_78_ap_vld),
    .c_79(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_79),
    .c_79_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_79_ap_vld),
    .c_80(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_80),
    .c_80_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_80_ap_vld),
    .c_81(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_81),
    .c_81_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_81_ap_vld),
    .c_82(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_82),
    .c_82_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_82_ap_vld),
    .c_83(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_83),
    .c_83_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_83_ap_vld),
    .c_84(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_84),
    .c_84_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_84_ap_vld),
    .c_85(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_85),
    .c_85_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_85_ap_vld),
    .c_86(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_86),
    .c_86_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_86_ap_vld),
    .c_87(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_87),
    .c_87_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_87_ap_vld),
    .c_88(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_88),
    .c_88_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_88_ap_vld),
    .c_89(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_89),
    .c_89_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_89_ap_vld),
    .c_90(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_90),
    .c_90_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_90_ap_vld),
    .c_91(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_91),
    .c_91_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_91_ap_vld),
    .c_92(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_92),
    .c_92_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_92_ap_vld),
    .c_93(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_93),
    .c_93_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_93_ap_vld),
    .c_94(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_94),
    .c_94_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_94_ap_vld),
    .c_95(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_95),
    .c_95_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_95_ap_vld),
    .c_96(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_96),
    .c_96_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_96_ap_vld),
    .c_97(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_97),
    .c_97_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_97_ap_vld),
    .c_98(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_98),
    .c_98_ap_vld(grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_98_ap_vld)
);

fir_wrap_fir_wrap_Pipeline_VITIS_LOOP_47_2 grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_ap_start),
    .ap_done(grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_ap_done),
    .ap_idle(grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_ap_idle),
    .ap_ready(grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_ap_ready),
    .m_axi_gmem_AWVALID(grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(gmem_AWREADY),
    .m_axi_gmem_AWADDR(grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(gmem_WREADY),
    .m_axi_gmem_WDATA(grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(gmem_RVALID),
    .m_axi_gmem_RREADY(grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(gmem_RDATA),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RFIFONUM(gmem_RFIFONUM),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(gmem_BVALID),
    .m_axi_gmem_BREADY(grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .sext_ln47_1(trunc_ln47_1_reg_1223),
    .sext_ln47(trunc_ln1_reg_1217),
    .len(len_read_reg_1200),
    .c_0(c_0),
    .c_98(c_98),
    .c_97(c_97),
    .c_96(c_96),
    .c_95(c_95),
    .c_94(c_94),
    .c_93(c_93),
    .c_92(c_92),
    .c_91(c_91),
    .c_90(c_90),
    .c_89(c_89),
    .c_88(c_88),
    .c_87(c_87),
    .c_86(c_86),
    .c_85(c_85),
    .c_84(c_84),
    .c_83(c_83),
    .c_82(c_82),
    .c_81(c_81),
    .c_80(c_80),
    .c_79(c_79),
    .c_78(c_78),
    .c_77(c_77),
    .c_76(c_76),
    .c_75(c_75),
    .c_74(c_74),
    .c_73(c_73),
    .c_72(c_72),
    .c_71(c_71),
    .c_70(c_70),
    .c_69(c_69),
    .c_68(c_68),
    .c_67(c_67),
    .c_66(c_66),
    .c_65(c_65),
    .c_64(c_64),
    .c_63(c_63),
    .c_62(c_62),
    .c_61(c_61),
    .c_60(c_60),
    .c_59(c_59),
    .c_58(c_58),
    .c_57(c_57),
    .c_56(c_56),
    .c_55(c_55),
    .c_54(c_54),
    .c_53(c_53),
    .c_52(c_52),
    .c_51(c_51),
    .c_50(c_50),
    .c_49(c_49),
    .c_48(c_48),
    .c_47(c_47),
    .c_46(c_46),
    .c_45(c_45),
    .c_44(c_44),
    .c_43(c_43),
    .c_42(c_42),
    .c_41(c_41),
    .c_40(c_40),
    .c_39(c_39),
    .c_38(c_38),
    .c_37(c_37),
    .c_36(c_36),
    .c_35(c_35),
    .c_34(c_34),
    .c_33(c_33),
    .c_32(c_32),
    .c_31(c_31),
    .c_30(c_30),
    .c_29(c_29),
    .c_28(c_28),
    .c_27(c_27),
    .c_26(c_26),
    .c_25(c_25),
    .c_24(c_24),
    .c_23(c_23),
    .c_22(c_22),
    .c_21(c_21),
    .c_20(c_20),
    .c_19(c_19),
    .c_18(c_18),
    .c_17(c_17),
    .c_16(c_16),
    .c_15(c_15),
    .c_14(c_14),
    .c_13(c_13),
    .c_12(c_12),
    .c_11(c_11),
    .c_10(c_10),
    .c_9(c_9),
    .c_8(c_8),
    .c_7(c_7),
    .c_6(c_6),
    .c_5(c_5),
    .c_4(c_4),
    .c_3(c_3),
    .c_2(c_2),
    .c_1(c_1)
);

fir_wrap_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .len(len),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

fir_wrap_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .y(y),
    .x(x),
    .coef(coef)
);

fir_wrap_gmem_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem_ARVALID),
    .I_ARREADY(gmem_ARREADY),
    .I_ARADDR(gmem_ARADDR),
    .I_ARLEN(gmem_ARLEN),
    .I_RVALID(gmem_RVALID),
    .I_RREADY(gmem_RREADY),
    .I_RDATA(gmem_RDATA),
    .I_RFIFONUM(gmem_RFIFONUM),
    .I_AWVALID(gmem_AWVALID),
    .I_AWREADY(gmem_AWREADY),
    .I_AWADDR(gmem_AWADDR),
    .I_AWLEN(gmem_AWLEN),
    .I_WVALID(gmem_WVALID),
    .I_WREADY(gmem_WREADY),
    .I_WDATA(grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_WDATA),
    .I_WSTRB(grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_WSTRB),
    .I_BVALID(gmem_BVALID),
    .I_BREADY(gmem_BREADY)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_ap_start_reg <= 1'b1;
        end else if ((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_ap_ready == 1'b1)) begin
            grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state20)) begin
            grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_ap_start_reg <= 1'b1;
        end else if ((grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_ap_ready == 1'b1)) begin
            grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_0_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_0 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_1 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_10_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_10 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_10;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_11_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_11 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_11;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_12_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_12 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_12;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_13_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_13 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_13;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_14_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_14 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_14;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_15_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_15 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_15;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_16_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_16 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_16;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_17_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_17 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_17;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_18_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_18 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_18;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_19_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_19 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_19;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_2_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_2 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_20_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_20 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_20;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_21_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_21 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_21;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_22_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_22 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_22;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_23_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_23 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_23;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_24_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_24 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_24;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_25_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_25 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_25;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_26_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_26 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_26;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_27_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_27 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_27;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_28_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_28 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_28;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_29_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_29 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_29;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_3_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_3 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_3;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_30_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_30 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_30;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_31_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_31 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_31;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_32_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_32 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_32;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_33_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_33 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_33;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_34_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_34 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_34;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_35_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_35 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_35;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_36_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_36 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_36;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_37_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_37 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_37;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_38_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_38 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_38;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_39_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_39 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_39;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_4_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_4 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_4;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_40_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_40 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_40;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_41_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_41 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_41;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_42_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_42 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_42;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_43_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_43 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_43;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_44_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_44 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_44;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_45_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_45 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_45;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_46_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_46 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_46;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_47_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_47 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_47;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_48_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_48 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_48;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_49_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_49 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_49;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_5_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_5 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_5;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_50_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_50 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_50;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_51_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_51 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_51;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_52_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_52 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_52;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_53_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_53 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_53;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_54_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_54 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_54;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_55_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_55 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_55;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_56_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_56 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_56;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_57_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_57 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_57;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_58_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_58 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_58;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_59_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_59 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_59;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_6_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_6 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_6;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_60_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_60 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_60;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_61_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_61 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_61;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_62_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_62 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_62;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_63_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_63 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_63;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_64_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_64 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_64;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_65_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_65 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_65;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_66_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_66 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_66;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_67_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_67 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_67;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_68_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_68 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_68;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_69_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_69 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_69;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_7_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_7 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_7;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_70_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_70 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_70;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_71_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_71 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_71;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_72_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_72 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_72;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_73_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_73 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_73;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_74_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_74 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_74;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_75_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_75 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_75;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_76_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_76 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_76;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_77_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_77 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_77;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_78_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_78 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_78;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_79_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_79 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_79;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_8_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_8 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_8;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_80_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_80 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_80;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_81_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_81 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_81;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_82_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_82 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_82;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_83_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_83 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_83;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_84_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_84 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_84;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_85_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_85 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_85;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_86_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_86 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_86;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_87_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_87 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_87;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_88_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_88 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_88;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_89_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_89 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_89;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_9_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_9 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_9;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_90_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_90 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_90;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_91_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_91 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_91;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_92_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_92 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_92;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_93_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_93 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_93;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_94_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_94 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_94;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_95_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_95 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_95;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_96_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_96 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_96;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_97_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_97 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_97;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_98_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        c_98 <= grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_c_98;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        empty_63_reg_1234 <= empty_63_fu_1169_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        len_read_reg_1200 <= len;
        trunc_ln1_reg_1217 <= {{x[63:2]}};
        trunc_ln31_reg_1206 <= trunc_ln31_fu_1120_p1;
        trunc_ln41_1_reg_1211 <= {{coef[63:2]}};
        trunc_ln47_1_reg_1223 <= {{y[63:2]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        zext_ln47_reg_1244[30 : 0] <= zext_ln47_fu_1186_p1[30 : 0];
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_ARREADY == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

always @ (*) begin
    if ((gmem_AWREADY == 1'b0)) begin
        ap_ST_fsm_state19_blk = 1'b1;
    end else begin
        ap_ST_fsm_state19_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

always @ (*) begin
    if ((grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_ap_done == 1'b0)) begin
        ap_ST_fsm_state21_blk = 1'b1;
    end else begin
        ap_ST_fsm_state21_blk = 1'b0;
    end
end

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

always @ (*) begin
    if ((gmem_BVALID == 1'b0)) begin
        ap_ST_fsm_state26_blk = 1'b1;
    end else begin
        ap_ST_fsm_state26_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_ARREADY == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((gmem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state26))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state26))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        gmem_ARADDR = sext_ln47_fu_1176_p1;
    end else if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        gmem_ARADDR = sext_ln41_fu_1154_p1;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        gmem_ARADDR = grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_ARADDR;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state11))) begin
        gmem_ARADDR = grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_ARADDR;
    end else begin
        gmem_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        gmem_ARLEN = zext_ln47_fu_1186_p1;
    end else if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        gmem_ARLEN = 32'd99;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        gmem_ARLEN = grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_ARLEN;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state11))) begin
        gmem_ARLEN = grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_ARLEN;
    end else begin
        gmem_ARLEN = 'bx;
    end
end

always @ (*) begin
    if ((((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state12)) | ((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        gmem_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        gmem_ARVALID = grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_ARVALID;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state11))) begin
        gmem_ARVALID = grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_ARVALID;
    end else begin
        gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        gmem_AWADDR = sext_ln47_1_fu_1190_p1;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        gmem_AWADDR = grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_AWADDR;
    end else begin
        gmem_AWADDR = 'bx;
    end
end

always @ (*) begin
    if (((gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        gmem_AWLEN = zext_ln47_reg_1244;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        gmem_AWLEN = grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_AWLEN;
    end else begin
        gmem_AWLEN = 'bx;
    end
end

always @ (*) begin
    if (((gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        gmem_AWVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        gmem_AWVALID = grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_AWVALID;
    end else begin
        gmem_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state26))) begin
        gmem_BREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        gmem_BREADY = grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_BREADY;
    end else begin
        gmem_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        gmem_RREADY = grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_RREADY;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state11))) begin
        gmem_RREADY = grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_m_axi_gmem_RREADY;
    end else begin
        gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        gmem_WVALID = grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_m_axi_gmem_WVALID;
    end else begin
        gmem_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state2))) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        gmem_blk_n_AW = m_axi_gmem_AWREADY;
    end else begin
        gmem_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        gmem_blk_n_B = m_axi_gmem_BVALID;
    end else begin
        gmem_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            if (((gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            if (((grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            if (((gmem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state26))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign empty_63_fu_1169_p3 = ((icmp_ln47_fu_1164_p2[0:0] == 1'b1) ? trunc_ln31_reg_1206 : 31'd0);

assign grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_ap_start = grp_fir_wrap_Pipeline_VITIS_LOOP_41_1_fu_512_ap_start_reg;

assign grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_ap_start = grp_fir_wrap_Pipeline_VITIS_LOOP_47_2_fu_717_ap_start_reg;

assign icmp_ln47_fu_1164_p2 = (($signed(len_read_reg_1200) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign sext_ln41_fu_1154_p1 = $signed(trunc_ln41_1_reg_1211);

assign sext_ln47_1_fu_1190_p1 = $signed(trunc_ln47_1_reg_1223);

assign sext_ln47_fu_1176_p1 = $signed(trunc_ln1_reg_1217);

assign trunc_ln31_fu_1120_p1 = len[30:0];

assign zext_ln47_fu_1186_p1 = empty_63_reg_1234;

always @ (posedge ap_clk) begin
    zext_ln47_reg_1244[31] <= 1'b0;
end

endmodule //fir_wrap
